class Levels():
    def maze_level_1(self) -> list:
        return [
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX",
            "X..............................OX",
            "X.XXX.XXX.XXXXXX.XXXXXX.XXX.XXX.X",
            "X.X X.X X......X.X....X.X X.X X.X",
            "X.XXX.X X.XXXXXX.X.XXXX.X X.XXX.X",
            "X.....XXX.X....X.X....X.XXX.....X",
            "XXXXX.......XX.X.X.XX.......XXXXX",
            "X.....XXXXX...........XXXXX.....X",
            "X.XXX.......XXXXXXXXX.......XXX.X",
            "X.....XXXXX...........XXXXX.....X",
            "X.XXX...O...XXXX.XXXX.......XXX.X",
            "X.X X.XXXXX.X  X.X  X.XXXXX.X X.X",
            "X.X X.X   X.X  X.X  X.X   X.X X.X",
            "X.X X.X   X.X  X.X  X.X   X.X X.X",
            "X.X X.XXXXX.X  X.X  X.XXXXX.X X.X",
            "X.XXX.......XXXX.XXXX...O...XXX.X",
            "X.....XXXXX...........XXXXX.....X",
            "X.XXX.......XXXXXXXXX.......XXX.X",
            "X.....XXXXX...........XXXXX.....X",
            "XXXXX.......XX.X.X.XX.......XXXXX",
            "X.....XXX.X....X.X....X.XXX.....X",
            "X.XXX.X X.XXXXXX.XXXXXX.X X.XXX.X",
            "X.X X.X X.X....X.X....X.X X.X X.X",
            "X.XXX.XXX.X.XX.X.X.XX.X.XXX.XXX.X",
            "XO..............................X",
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX"
        ]
    def maze_level_2(self) -> list:

        return [
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX",
            "XO........XX...................OX",
            "X.XXXXXXX.XX.XXXXXXXXXX.XXXXXXX.X",
            "X.X.....X....X........X.X.....X.X",
            "X.X.XXX.XXXX.X.XXXXXX.X.X.XXX.X.X",
            "X...X.X......X....X...X.X.X...X.X",
            "XXX.X.XXXXXXXXXXX.X.XXX.X.X.XXX.X",
            "X...X.............X.....X.X.....X",
            "X.XXXXXXXX.XXXXXXXXXXX.XX.XXXXX.X",
            "X........X.....X.......XX.......X",
            "X.XXXXXX.XXXXX.X.XXXXXXXXXXXXXX.X",
            "X.X    X.....X.X.X.....X........X",
            "X.X XX XXXXX.X.X.X.XXX.X.XXXX.X.X",
            "X.X XX X   X.X.X.X.X X.X.X  X.X.X",
            "X.X XX XXXXX.X.X.X.XXX.X.XXXX.X.X",
            "X.X    X.....X.X.X............X.X",
            "X.XXXXXX.XXXXX.X.XXXXXXXXXXXXXX.X",
            "X........X.....X.......XX.......X",
            "X.XXXXXXXX.XXXXXXXXXXX.XX.XXXXX.X",
            "X...X.............X.....X.X.....X",
            "XXX.X.XXXXXXXXXXX.X.XXX.X.X.XXX.X",
            "X...XOX......X....X...X.X.X...X.X",
            "X.X.XXX.XXXX.X.XXXXXX.X.X.XXX.X.X",
            "X.X.....X....X........X.X.....X.X",
            "XO........XX...................OX",
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX"
        ]
    def maze_level_3(self) -> list:

        return [
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX",
            "XO..............................X",
            "X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X",
            "X.X...........................X.X",
            "X.X.XXXXXXXXXXXXXXXXXXXXXXX.X.X.X",
            "X.X.X.....................X.X.X.X",
            "X.X.X.XXXXXXXXXXXXXXXXX.X.X.X.X.X",
            "X.X.X.X...............X.X.X.X.X.X",
            "X.X.X.X.XXXXXX.XXXXXX.X.X.X.X.X.X",
            "X.X.X.X.X..........OX.X.X.X.X.X.X",
            "X.X.X.X.X.XXXXXXXXX.X.X.X.X.X.X.X",
            "X.X.X.X.X.X       X.X.X.X.X.X.X.X",
            "X.X.X.X.X.X XXXXX X.X.X.X.X.XOX.X",
            "X.X.X.X.X.X XXXXX X.X.X.X.X.X.X.X",
            "X.X...X.X.X       X.X.X.X.X.X.X.X",
            "X.X.X.X.X.XXXXXXXXX.X.X.X.X.X.X.X",
            "X.X.X.X.X...........X.X.X.X.X.X.X",
            "X.X.X.X.XXXXXX..XXXXX.X.X.X.X.X.X",
            "X.X.X.X.................X.X.X.X.X",
            "X.X.X.XXXXXXXXXXXXXXXXX.X.X.X.X.X",
            "X.X.X.....................X.X.X.X",
            "X.X.XXXXXXXXXXXXXXXXXXXXXXX.X.X.X",
            "X.X...........................X.X",
            "X.XX.XXXXXXXXXXXXXXXXXXXXXXX.XX.X",
            "XO..............................X",
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX"
        ]
    
    def maze_level_4(self) -> list:
        return [
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX",
            "XO.............XO..............OX",
            "X.XXXXXXXXXXX.XX.XXXXXXXXXXXXXX.X",
            "X.X.........X....X............X.X",
            "X.X.XXXXXXX.XXXXXX.XXXXXXXXXX.X.X",
            "X.X.X.....X........X........X.X.X",
            "X...X.XXX.XXXXXXXXXX.XXXXXX.X...X",
            "XXX.X.X.................X.X.XXX.X",
            "X...X.X.XXXXXXXXXXXXXXX.X.X...X.X",
            "X.XXX.X.X.............X.X.XXX.X.X",
            "X.....X.X.XXXXXXXXXXX.X.X.....X.X",
            "X.XXXXX.X.X   XXX   X.X.XXXXX.X.X",
            "X.X.....X.X   X X   X.X.....X.X.X",
            "X.X.XXXXX.X   X X   X.XXXXX.X.X.X",
            "X.X.X.....XXXXXXXXXXX.....X.X.X.X",
            "X.X.X.XXXXXXXXXXXXXXX.XXX.X.X.X.X",
            "X.X.X........X X.......OX.X.X.X.X",
            "X.X.XXXXXXXX.X X.XXXXXXXX.X.X.X.X",
            "X.X..........X X..........X.X.X.X",
            "X.XXXXXXXXXX.X X.XXXXXXXXXX.X.X.X",
            "X............X X..............X.X",
            "X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X",
            "X...............................X",
            "X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.X",
            "XO.............................OX",
            "XXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXX"
        ]